<a href="https://colab.research.google.com/github/zihvvan/DataAnalysis/blob/main/zihvvan/ch05_02%2B03%2B04_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [12]:
arr1 = np.arange(1, 4) # 1, 2, 3
arr2 = np.arange(4, 7) # 4, 5, 6
np.concatenate([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

In [13]:
np.concatenate([arr1, arr2, arr1, arr2])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [14]:
arr1 = arr1.reshape(3, 1)
arr2 = arr2.reshape(3, 1)

np.concatenate([arr1, arr2])
np.concatenate([arr1, arr2], axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [15]:
np.concatenate([arr1, arr2], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
a1 = np.ones((2, 3))
a2 = np.zeros((2, 2))
np.hstack((a1, a2))

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [18]:
# b1 = np.ones((2, 3))
b1 = np.ones_like(a1)
b2 = np.zeros((3, 3))
np.vstack((b1, b2))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
c1 = np.ones((3, 4))
c2 = np.zeros_like(c1)
np.dstack((c1, c2)) # 행, 열 길이 같고, 가장 마지막 (안쪽의) 차원이 1증가하면서 합쳐진다

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [27]:
# c = np.stack([c1, c2])
np.stack([c1, c2], axis=0) # 행기준
c

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [26]:
np.stack([c1, c2], axis=-1) # 차원을 추가하면서 합쳐지는 (dstack)
np.stack([c1, c2], axis=2)

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [25]:
np.stack([c1, c2], axis=1) # 열기준

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [28]:
# r_ -> hstack. 1,2,3 / 4,5,6
np.r_[np.arange(1,4), np.arange(4,7)]

array([1, 2, 3, 4, 5, 6])

In [29]:
np.r_[np.arange(1,4), np.arange(4,7), np.arange(4,7)]

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

In [30]:
np.c_[np.arange(1,4), np.arange(4,7)]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
np.arange(1,4)[:, np.newaxis], np.arange(4,7)[:, np.newaxis]

(array([[1],
        [2],
        [3]]), array([[4],
        [5],
        [6]]))

In [32]:
np.concatenate((np.arange(1,4)[:, np.newaxis], np.arange(4,7)[:, np.newaxis]), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
# a = np.arange(6).reshape(2, -1)
a = np.arange(6).reshape(3, -1)
print(np.tile(a,3)) # 모양을 지키면서 반복 
np.repeat(a,(3)) # flattern 시킨 다음에,  반복

[[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [4 5 4 5 4 5]]


array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [36]:
arr = np.arange(7) # 0, 1, 2, 3, 4, 5, 6
arr

array([0, 1, 2, 3, 4, 5, 6])

In [37]:
np.array_split(arr, 3)

[array([0, 1, 2]), array([3, 4]), array([5, 6])]

In [38]:
arr = np.arange(6)
np.split(arr, 3) # array_split -> 되는대로 3등분, split : 엄격하게 약수로 맞게 입력해야 쪼개줌

[array([0, 1]), array([2, 3]), array([4, 5])]

In [39]:
arr = np.arange(1, 19).reshape(-1, 3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [40]:
# np.array_split(arr, 3) # 행 방향으로 짜름
np.array_split(arr, 3, axis=0) # 행 방향으로 짜름

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]]), array([[13, 14, 15],
        [16, 17, 18]])]

In [41]:
np.array_split(arr, 3, axis=1) # 행 방향으로 짜름

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]), array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [44]:
# 브로그캐스팅 : 크기가 작은 배열을 자동으로 반복확장하여 크기가 큰 배열에 맞추는 방법
x = np.arange(5)
x + 1

array([1, 2, 3, 4, 5])

In [46]:
x + np.ones_like(x) * 1

array([1, 2, 3, 4, 5])

In [47]:
x + 10

array([10, 11, 12, 13, 14])

In [48]:
np.ones_like(x) * 10

array([10, 10, 10, 10, 10])

In [51]:
# x + np.ones_like(x) * 10
x + np.full_like(x, 10)

array([10, 11, 12, 13, 14])

In [52]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [53]:
y = np.arange(5).reshape(-1, 1)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [54]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [55]:
x = np.arange(1, 5) # 1, 2, 3, 4

In [56]:
np.sum(x), x.sum()

(10, 10)

In [57]:
x.min(), x.max()

(1, 4)

In [59]:
x.argmin(), x.argmax()

(0, 3)

In [60]:
x.mean()

2.5

In [61]:
np.median(x)

2.5

In [62]:
np.any(x > 4), np.any(x > 2)

(False, True)

In [63]:
np.all(x > 4), np.all(x > 2), np.all(x >=0)

(False, False, True)

In [64]:
x = np.array(((1, 1), (2,2)))
x

array([[1, 1],
       [2, 2]])

In [65]:
x.sum()

6

In [67]:
x.sum(axis=0) # 행 내부에 있는 열들간의 연산, 행의 대푯값 (axis=0)

array([3, 3])

In [68]:
x.sum(axis=1) # 행 내부에 있는 열들간의 연산, 행의 대푯값 (axis=1)

array([2, 4])

In [71]:
a = np.random.randint(1, 20, 12).reshape(3, -1)
a

array([[12, 18, 16, 17],
       [16, 17,  5, 18],
       [ 7, 14, 11,  9]])

In [73]:
np.sort(a) # 행을 그대로, 열들 간의 정리. axis = 0
np.sort(a, axis=1) # 행을 그대로, 열들 간의 정리. axis = 1
np.sort(a, axis=-1) # 행을 그대로, 열들 간의 정리. axis = -1

array([[12, 16, 17, 18],
       [ 5, 16, 17, 18],
       [ 7,  9, 11, 14]])

In [75]:
np.sort(a, axis=0) # 열을 그대로, 행들 간의 정리. axis = 0

array([[ 7, 14,  5,  9],
       [12, 17, 11, 17],
       [16, 18, 16, 18]])

In [76]:
a.sort(axis=1) # in-place

In [77]:
a

array([[12, 16, 17, 18],
       [ 5, 16, 17, 18],
       [ 7,  9, 11, 14]])

In [78]:
np.argsort(a)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [80]:
np.argsort(a, axis=0)

array([[1, 2, 2, 2],
       [2, 0, 0, 0],
       [0, 1, 1, 1]])

In [81]:
x = np.random.randint(0, 100, 12).reshape(3, -1)
x

array([[70, 72, 92,  9],
       [35, 65, 28, 69],
       [34, 25, 33, 51]])

In [82]:
x[:, np.argsort(x[1])]

array([[92, 70, 72,  9],
       [28, 35, 65, 69],
       [33, 34, 25, 51]])

In [83]:
x=np.random.randint(-30, 30, 30)
x

array([ 14,   8,  -7, -30,  17, -29, -30,   9, -20, -19,   4, -28, -29,
        20,   1, -21,   3,  -3,  -5, -11,  10,  17,  10, -13,  -7,   3,
        -6,  -2,   4,  17])

In [84]:
len(x)

30

In [86]:
np.mean(x), x.mean()

(-4.1, -4.1)

In [87]:
np.var(x)

242.82333333333327

In [88]:
np.std(x)

15.582789651834913

In [89]:
np.max(x), np.min(x)

(20, -30)

In [91]:
np.median(x) # 짝수개일 경우, 두 값의 평균을 쓴다

-2.5

In [92]:
np.quantile(x, 0), np.percentile(x, 0) # 최솟값

-30

In [94]:
# 사분위수 => 1을 최대로 봤을 때의 비율수. 1/4, 2/4, 3/4...
# 백문위수는 100을 최대로 봤을 때의 값을 입력
np.quantile(x, 1/4), np.percentile(x, 25) # 1사분위수, 25백분위수

(-17.5, -17.5)

In [96]:
np.quantile(x, 2/4), np.percentile(x, 50) # 2사분위수, 50백분위수, 중앙값

(-2.5, -2.5)

In [97]:
np.quantile(x, 3/4), np.percentile(x, 75) # 3사분위수, 75백분위수

(8.75, 8.75)

In [98]:
np.quantile(x, 4/4), np.percentile(x, 100) # 최댓값

(20.0, 20.0)

In [99]:
# np.random.seed(0) # 이후 나오는 랜덤값들이 순서가 일치
np.random.seed(10) # 이후 나오는 랜덤값들이 순서가 일치

In [100]:
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [101]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
np.random.shuffle(x)

In [103]:
x

array([5, 3, 4, 7, 6, 8, 9, 2, 1, 0])

In [105]:
np.random.choice(x, 5, replace=False) # x 배열 안의 있는 값 중에 5개를 추출(비복원)

array([5, 2, 8, 4, 7])

In [106]:
np.random.choice(5, 5, replace=False)

array([0, 4, 2, 1, 3])

In [108]:
np.random.choice(np.arange(1, 46), 6, replace=False)

array([34, 27, 38,  8, 39, 24])

In [110]:
np.random.choice(np.arange(1, 7), 6)
np.random.choice(np.arange(1, 7), 6, replace=True)

array([2, 1, 5, 5, 1, 3])

In [111]:
np.random.choice(np.arange(1, 7), 6, p=[0, 0, 0, 0.6, 0.2, 0.2])

array([4, 5, 4, 5, 4, 4])

In [113]:
np.random.randn(10) # 0 평균, 표준편자 -1. -2.+2 => 99.9% 0에 가까울수록 값들이 더 많이 등장

array([ 1.75223653,  0.34854848, -0.02290254, -0.96170169,  0.0792365 ,
       -0.39327207, -0.60099441, -0.59484183, -1.65773667, -0.00507017])

In [114]:
np.random.randn(3, 5)

array([[ 0.79305654, -0.88911776, -0.9978168 ,  0.66989397,  0.64851164],
       [ 0.02573462,  0.58660498,  0.28408516, -1.33168955,  1.27310627],
       [ 0.40924504, -0.60747309,  0.93400955, -1.84373609,  0.47805208]])

In [115]:
np.random.randint(10) # 최소 0, low

7

In [117]:
np.random.randint(10, size = 100) # 최소 0, 최대 low, size = 100

array([1, 5, 4, 5, 4, 3, 4, 4, 1, 1, 2, 1, 1, 2, 2, 2, 5, 8, 1, 7, 1, 7,
       1, 8, 0, 6, 7, 5, 1, 2, 6, 1, 5, 8, 0, 3, 9, 6, 3, 0, 2, 8, 9, 8,
       0, 7, 7, 4, 6, 3, 4, 5, 3, 5, 9, 2, 3, 2, 2, 5, 8, 4, 1, 6, 7, 1,
       7, 1, 2, 9, 2, 7, 4, 6, 7, 3, 2, 3, 9, 2, 5, 0, 7, 2, 6, 5, 7, 3,
       7, 0, 3, 6, 0, 7, 2, 9, 5, 1, 0, 2])

In [118]:
np.random.randint(1, 10) # 최소 low, 최대 high

4

In [116]:
np.random.randint(1, 10, 100) # 최소 low, 최대 high, size

array([9, 8, 8, 7, 3, 1, 5, 6, 5, 7, 1, 5, 7, 5, 9, 1, 8, 2, 8, 2, 2, 6,
       6, 1, 9, 4, 8, 2, 6, 3, 4, 5, 6, 8, 7, 9, 1, 5, 7, 4, 6, 4, 9, 4,
       1, 7, 3, 4, 2, 5, 1, 6, 1, 9, 2, 4, 7, 1, 1, 7, 6, 8, 5, 1, 1, 3,
       3, 2, 7, 7, 8, 4, 1, 8, 8, 1, 3, 3, 1, 6, 9, 1, 6, 4, 7, 8, 9, 1,
       7, 1, 2, 1, 2, 5, 1, 2, 8, 4, 1, 9])

In [124]:
# 가격이 1만원 주식
price = 10000
# 일간 수익률 -> 기댓값(평균) 0, 표준편자 1%=0.01 (표준정규분포)
days = 250
daily_earning_rate = np.random.randn(days) / 100
print(daily_earning_rate)
# 250일 동안의 주가를 무작위로 생성
# 주가 -> 전일 가격 * (1 + 당일 수익률)
price_arr = np.empty(days)
for i, v in enumerate(daily_earning_rate):
    print(v)
    price *= (1 + v)
    print(price)
    price_arr[i] = price
    print(price_arr[i])
    print(price_arr)
price_arr

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
  1.02163615e+004  1.01485296e+004  1.02705209e+004  1.02484826e+004
  1.02285197e+004  1.03467115e+004  1.04190882e+004  1.06288788e+004
  1.06200996e+004  1.08227708e+004  1.08140557e+004  1.07198242e+004
  1.06160753e+004  1.04499512e+004  1.03290425e+004  1.01852692e+004
  1.02347088e+004  1.01840987e+004  1.03935593e+004  1.02749926e+004
  1.02353112e+004  1.03398022e+004  1.03761784e+004  1.04884944e+004
  1.04142261e+004  1.04895435e+004  1.03730802e+004  1.05066902e+004
  1.04012030e+004  1.02105196e+004  1.02395480e+004  1.02428482e+004
  1.01127319e+004  1.00756417e+004  9.93142240e+003  1.00607251e+004
  1.01205221e+004  1.01459769e+004  1.02735726e+004  1.02052016e+004
  1.01056453e+004  9.95546288e+003  9.91044815e+003  9.89628557e+003
  9.69366171e+003  9.80871124e+003  9.69972010e+003  9.58004329e+003
  9.57360826e+003  9.55703289e+003  9.66981360e+003  9.73235040e+003
  9.85981996e+003  9.77266499e+003  9.87155329e+003  9.90641892e+00

array([10210.56088367, 10257.40697707, 10211.80726189, 10179.21755147,
       10046.13862758, 10149.34260332, 10331.51805012, 10464.93561978,
       10405.43801145, 10399.76966555, 10259.10243158, 10334.23175549,
       10226.35039885, 10259.7191049 , 10274.98923913, 10320.08980131,
       10276.99782801, 10283.00795046, 10237.40254279, 10054.41107757,
        9949.5338768 ,  9916.97857355, 10061.17884195, 10280.01817161,
       10332.30479556, 10422.74761899, 10377.76103478, 10278.83193122,
       10332.54540061, 10247.19116632, 10209.84016192, 10318.81163521,
       10343.09814145, 10345.5208278 , 10368.07707745, 10242.44507426,
       10242.71842947, 10274.35737118, 10228.58232345, 10219.82474066,
       10199.39998073, 10238.84219166, 10346.60223191, 10434.41065557,
       10440.77132837, 10115.78718754, 10093.83464617, 10236.37545228,
       10283.83330858, 10148.81882711, 10173.56896907, 10319.93281315,
       10216.36148074, 10148.52956166, 10270.52088826, 10248.48256263,
      

In [125]:
x = np.random.randint(1, 10, 100)
x

array([3, 4, 5, 1, 5, 1, 3, 6, 9, 7, 5, 5, 6, 6, 1, 1, 6, 4, 8, 4, 2, 4,
       4, 8, 8, 5, 1, 2, 7, 3, 9, 5, 8, 3, 3, 5, 1, 8, 5, 2, 4, 6, 1, 3,
       1, 7, 4, 4, 3, 5, 7, 3, 4, 8, 7, 9, 7, 4, 3, 2, 3, 9, 1, 1, 2, 9,
       2, 3, 1, 5, 6, 8, 7, 1, 6, 6, 4, 9, 6, 9, 2, 9, 9, 8, 8, 2, 8, 6,
       1, 6, 6, 6, 2, 9, 3, 2, 8, 8, 3, 5])

In [126]:
np.unique(x)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
np.unique(x, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([13, 10, 13, 11, 11, 13,  7, 12, 10]))

In [130]:
key, value = np.unique(x, return_counts=True)
print(key)
print(value)

[1 2 3 4 5 6 7 8 9]
[13 10 13 11 11 13  7 12 10]


In [131]:
# 2개의 시퀀스를, 인덱스로 묶어줌 zip
list(zip(key, value))

[(1, 13),
 (2, 10),
 (3, 13),
 (4, 11),
 (5, 11),
 (6, 13),
 (7, 7),
 (8, 12),
 (9, 10)]

In [132]:
dict(list(zip(key, value)))

{1: 13, 2: 10, 3: 13, 4: 11, 5: 11, 6: 13, 7: 7, 8: 12, 9: 10}

In [133]:
dict(zip(key, value))

{1: 13, 2: 10, 3: 13, 4: 11, 5: 11, 6: 13, 7: 7, 8: 12, 9: 10}

In [134]:
dict(zip(*np.unique(x, return_counts=True)))

{1: 13, 2: 10, 3: 13, 4: 11, 5: 11, 6: 13, 7: 7, 8: 12, 9: 10}

In [135]:
x = np.random.randint(30, size = 10)
x

array([26, 23,  7, 18, 26, 22, 10,  2, 27, 12])

In [136]:
dict(zip(*np.unique(x, return_counts=True)))

{2: 1, 7: 1, 10: 1, 12: 1, 18: 1, 22: 1, 23: 1, 26: 2, 27: 1}

In [137]:
np.bincount(x, minlength = 30)

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 2, 1, 0, 0])

In [138]:
np.arange(30), np.bincount(x, minlength = 30)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 1, 0, 0, 2, 1, 0, 0]))

In [139]:
dict(zip(np.arange(30), np.bincount(x, minlength=30)))

{0: 0,
 1: 0,
 2: 1,
 3: 0,
 4: 0,
 5: 0,
 6: 0,
 7: 1,
 8: 0,
 9: 0,
 10: 1,
 11: 0,
 12: 1,
 13: 0,
 14: 0,
 15: 0,
 16: 0,
 17: 0,
 18: 1,
 19: 0,
 20: 0,
 21: 0,
 22: 1,
 23: 1,
 24: 0,
 25: 0,
 26: 2,
 27: 1,
 28: 0,
 29: 0}